version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Flutter doctor
          command: flutter doctor -v
      - run:
          name: Run widget tests
          command: flutter test
